# Generated by Django 3.2.9 on 2021-11-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211122_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
