# Generated by Django 3.2.9 on 2021-11-22 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211122_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='code',
        ),
        migrations.RemoveField(
            model_name='room',
            name='guest_can_pause',
        ),
        migrations.RemoveField(
            model_name='room',
            name='host',
        ),
        migrations.RemoveField(
            model_name='room',
            name='votes_to_skip',
        ),
    ]
