# Generated by Django 3.2.9 on 2021-11-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_room_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
